version: '2'

services:

  php7fpm:
    build: ./build/php7fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/sv/php7.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"

  lb1:
    image: haproxy:1.7.1
    container_name: lb1-haproxy
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./config/lb/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "80:80"
      - "8000:8000"

  sv1:
    image: nginx:1.11.5
    container_name: sv1-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/sv/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/sv/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8001:80"
      - "4431:443"

  sv2:
    image: nginx:1.11.5
    container_name: sv2-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/sv/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/sv/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "8002:80"
      - "4432:443"
