version: '3'

services:

  php7fpm:
    image: php:7.1.7-fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
#      - ./html:/usr/share/nginx/html
      - ./php7-ini/php7-upload.ini:/usr/local/etc/php/php.ini
      - ./php7-ext/phalcon-v3.2.1.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon-v3.2.1.so
      - ./php7-ini/20-phalcon.ini:/usr/local/etc/php/conf.d/20-phalcon.ini
      - ./php7-ext/mongodb-v1.2.9.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mongodb-v1.2.9.so
      - ./php7-ini/20-mongodb.ini:/usr/local/etc/php/conf.d/20-mongodb.ini
    ports:
      - "9000:9000"