version: '3'

services:

  php7fpm:
    build: ./build/php7fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./extension/php7-ini/php7-upload.ini:/usr/local/etc/php/php.ini
      - ./extension/php7-ext/phalcon-v3.2.1.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon-v3.2.1.so
      - ./extension/php7-ini/20-phalcon.ini:/usr/local/etc/php/conf.d/20-phalcon.ini
      - ./extension/php7-ext/mongodb-v1.2.9.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mongodb-v1.2.9.so
      - ./extension/php7-ini/20-mongodb.ini:/usr/local/etc/php/conf.d/20-mongodb.ini
    ports:
      - "9000:9000"

  mariadb:
    image: mariadb:10.3.0
    command: mysqld --innodb-buffer-pool-size=20M
    container_name: docker-mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
#      - MYSQL_DATABASE=db_admin
#      - MYSQL_USER=admin
#      - MYSQL_PASSWORD=123456
      - TERM=xterm
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:3.5.10
    container_name: docker-mongo
    restart: always
    environment:
      - AUTH=no
      - TERM=xterm
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles
#   command: mongod --smallfiles --auth

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7.3-1
    container_name: docker-phpmyadmin
    restart: always
    environment:
      - TERM=xterm
      - PMA_HOST=mariadb
#      - PMA_USER=admin
#      - PMA_PASSWORD=123456
    links:
      - "mariadb:mariadb"
    ports:
      - "8080:80"

  nginx:
    image: nginx:1.13.3
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    environment:
      - TERM=xterm
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/vhosts:/etc/nginx/conf.d/vhosts
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"