version: '3'

services:

  php7fpm:
    image: php:7.1.7-fpm
    container_name: docker-php7fpm
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./extension/php7-ini/php7-upload.ini:/usr/local/etc/php/php.ini
      - ./extension/php7-ext/phalcon-v3.2.1.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon-v3.2.1.so
      - ./extension/php7-ini/20-phalcon.ini:/usr/local/etc/php/conf.d/20-phalcon.ini
      - ./extension/php7-ext/mongodb-v1.2.9.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mongodb-v1.2.9.so
      - ./extension/php7-ini/20-mongodb.ini:/usr/local/etc/php/conf.d/20-mongodb.ini
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.13.3
    container_name: docker-nginx
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"