
version: '2'

services:

  phpfpm:
    image: drivestudio/phalcon-php7-fpm:7.0.13
    container_name: docker-phpfpm
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.11.5
    container_name: docker-nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    links:
      - phpfpm
    ports:
      - "8000:80"
