version: '2'

services:

  php7fpm:
    image: php:7.1.3-fpm
    container_name: docker-php7fpm
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./extension/php7-ext/phalcon3-7.1.3.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/phalcon3-7.1.3.so
      - ./extension/php7-ini/20-phalcon3-7.1.3.ini:/usr/local/etc/php/conf.d/20-phalcon3-7.1.3.ini
      - ./extension/php7-ext/mongodb-1.2.8.so:/usr/local/lib/php/extensions/no-debug-non-zts-20160303/mongodb-1.2.8.so
      - ./extension/php7-ini/20-mongodb-1.2.8.ini:/usr/local/etc/php/conf.d/20-mongodb-1.2.8.ini
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.11.10
    container_name: docker-nginx
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"
