version: '2'

services:

  phpfpm:
    image: php:7.0.14-fpm
    container_name: docker-phpfpm
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.11.5
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
