services:

  phpfpm:
    image: php:7.0.13-fpm
    container_name: docker-phpfpm
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.11.5
    container_name: docker-nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
