version: '2'

services:

  php7fpm:
    image: php:7.1.4-fpm
    container_name: docker-php7fpm
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.13.0
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    links:
      - "php7fpm:phpfpm"
    ports:
      - "80:80"
      - "443:443"
