version: '3'

services:

  php7fpm:
    build: ./build
    container_name: docker-php7fpm
    restart: always
    volumes:
      - ./php7-ext:/usr/local/lib/php/extensions/no-debug-non-zts-20160303
      - ./php7-ini:/usr/local/etc/php/conf.d