service:
  nginx:
    image: nginx:1.11.5
    container_name: docker-nginx
    working_dir: /usr/share/nginx/html    
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf      
    ports:
      - "80:80"
      - "443:443"
