services:

  redis:
    image: redis:3.2.4
    container_name: docker-redis
    restart: always
    volumes:
      - ./data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"
