version: '3'

services:

  redis:
    image: redis:4.0.1
    container_name: docker-redis
    restart: always
    volumes:
      - ./data:/data
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"